todoproject/todo/urls.py
from django.urls import path

from. import views


app_name = 'todo'

urlpatterns = [
    path('',views.home,name='home'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('',views.TaskListView.as_view(),name='home'),
    path('cvdetails/<int:pk>/',views.TaskDetailView.as_view(),name='cvdetails'),
    path('cvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cvupdate'),
    path('cvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cvdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todoproject/todo/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    priority = models.IntegerField()
    date = models.DateTimeField()

    def __str__(self):
        return self.name

todoproject/todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from todo.frorms import TaskForm

from.models import Task

# class basedinte imports 
from django.views.generic import ListView, DetailView,UpdateView,DeleteView



# class based 
class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'tasks'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todo:cvdetails', kwargs={'pk': self.object.id})


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todo:home')


# function based 

def home(request):
     
    tasks = Task.objects.all()
    print(tasks)

   
    if request.method == 'POST':
        name = request.POST.get('task')
        priority = request.POST.get('priority')
        date = request.POST.get('date')

        tasks = Task.objects.create(name=name, priority=priority,date=date)
        tasks.save()
        return redirect('todo:home')
    
    context = {
        'tasks': tasks
    }

    return render(request, 'home.html',context=context)


def delete(request, id):

    if request.method == 'POST':
        if Task.objects.filter(id=id).exists():
            task = Task.objects.get(id=id)
            task.delete()
            return redirect('todo:home')
        else:
            pass
    
    return render(request,'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    form = TaskForm(request.POST or None, instance=task)

    if form.is_valid():
        form.save()
        return redirect('todo:home')
    
    context = {
        'form': form
    }

    return render(request, 'update.html', context=context)
    

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 shadow mt-5 p-3">
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure?</p>
                <input type="submit" class="btn-danger" value="Delete">
            </form>
        </div>
    </div>
</div>
    
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9 mt-5">
            <div class="card mb-3 shadow">
                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p class="">{{task.priority}}</p>
                    <p>{{task.date}}</p>
                    <a class="btn btn-primary" href="{% url 'todo:cvupdate' task.id %}">Edit</a>
                    <a class="btn btn-danger" href="{% url 'todo:cvdelete' task.id %}">Delete</a>
                </div>   
            </div> 
        </div>
    </div>
</div>

{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text"><h1>ToDo</h1></div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6 mt-5">
            <form action="" method="POST" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group mb-1 p-1">
                    <input type="text" class="form-control" name="task" placeholder="Enter your task"> 
                </div>
                <div class="form-group mb-1 p-1">
                    <input type="text" name="priority" placeholder="Priority" class="form-control">
                </div>
                <div class="form-group mb-1 p-1">
                    <input type="date" name="date" placeholder="Add date" class="form-control">
                </div>    
                    <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-6 mt-5">
            <h1>Task to be completed</h1>
            {% for task in tasks %}
                <div class="card mb-3 shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{task.name}}</h5>
                        <p class="">{{task.priority}}</p>
                        <p>{{task.date}}</p>
                        <a class="btn btn-primary" href="{% url 'todo:update' task.id %}">Edit</a>
                        <a class="btn btn-danger" href="{% url 'todo:cvdelete' task.id %}">Delete</a>
                    </div>   
                </div> 
            {% endfor %}
        </div>
    </div>
</div>
    
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9 mt-5">
            <form action="" method="POST" class="form-group mb-1 p-2 shadow">
                <h3>Please update your Task</h3>
                <div class="form-group mb-1 p-1">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <input type="submit" value="Save" class="btn btn-success">
            </form>
            
        </div>
    </div>
</div>

{% endblock %}